# This is a basic workflow to help you get started with Actions

name: Check-in

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        include:
          - tnt_username: TNT_USERNAME
            tnt_password: TNT_PASSWORD
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.8
      - name: 'Install requirements'
        run: pip install -r ./Spider/requirements.txt
      - name: 'Working'
        env:
          TNT_USERNAME: ${{ secrets[matrix.tnt_username] }}
          TNT_PASSWORD: ${{ secrets[matrix.tnt_password] }}
        run: |
          sudo cp -p ./chrome/chromedriver /usr/bin/
          chmod -R 777 /usr/bin/chromedriver
          python ./check_in.py
        shell: bash
